#! /usr/bin/env bash

INPUT_DIR="examples"
# INPUT_DIR="input"

ROOT_DIR="$(dirname "${BASH_SOURCE[0]}")"

function run_file() {
    blitzc-debug "$1" >/dev/null 2>&1

    OUT=$(echo $?)

    if [ $OUT == 0 ]; then
        echo "SUCCESS: $1"
    else
        echo "FAIL: $1"
    fi
}

function test_files() {
    for file in "$ROOT_DIR/$INPUT_DIR"/*; do
        run_file "$file" &
    done
}

if [ "$1" == "" ]; then
    test_files
elif [ "$1" == "-p" ]; then
    shopt -s nullglob
    pattern="$ROOT_DIR/$INPUT_DIR/*$2*"
    matches=($pattern)

    if ((${#matches[@]})); then
        first_match="${matches[0]}"
        run_file "$first_match"
    else
        echo "No file $pattern found"
        exit 0
    fi
elif [ "$1" == "build" ]; then
    zig build
    test_files
else
    if [[ "$1" != *\.blitz ]]; then
        echo "expected filename with [.blitz] extension"
        exit 0
    fi

    run_file "$1"
fi

wait
